// Generated by CoffeeScript 1.6.3
exports.tabToSpaces = function(s, spaceCount) {
  var char, chars, i, k, len, out, spaces, _i, _j;
  if (spaceCount == null) {
    spaceCount = 8;
  }
  chars = s.split("");
  len = chars.length;
  out = "";
  for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
    char = chars[i];
    if (char === "\t") {
      spaces = spaceCount - (out.length % spaceCount);
      for (k = _j = 0; 0 <= spaces ? _j < spaces : _j > spaces; k = 0 <= spaces ? ++_j : --_j) {
        out += " ";
      }
    } else {
      out += char;
    }
  }
  return out;
};

exports.padLeft = function(s, length, char) {
  var fill, pad, _i;
  if (char == null) {
    char = ' ';
  }
  fill = length - s.length;
  pad = "";
  if (fill > 0) {
    for (_i = 0; 0 <= fill ? _i < fill : _i > fill; 0 <= fill ? _i++ : _i--) {
      pad += " ";
    }
    return pad + s;
  } else {
    return pad;
  }
};
